// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUggyWXIxDpu8Bfg0I_foyDrJXUWhPS-w',
    appId: '1:896887756807:web:bd2d2b162331af819572a2',
    messagingSenderId: '896887756807',
    projectId: 'codecelixtaskmanager-f8557',
    authDomain: 'codecelixtaskmanager-f8557.firebaseapp.com',
    storageBucket: 'codecelixtaskmanager-f8557.firebasestorage.app',
    measurementId: 'G-X9DENGN9W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAWV_KHsXec3kzPAlnz52SxSMHWAIGA8k',
    appId: '1:896887756807:android:4d975fa6b9c4370b9572a2',
    messagingSenderId: '896887756807',
    projectId: 'codecelixtaskmanager-f8557',
    storageBucket: 'codecelixtaskmanager-f8557.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwvePvF7jb04K6LisfoBoonR0vBYGoJX8',
    appId: '1:896887756807:ios:54a1115ece543f639572a2',
    messagingSenderId: '896887756807',
    projectId: 'codecelixtaskmanager-f8557',
    storageBucket: 'codecelixtaskmanager-f8557.firebasestorage.app',
    iosBundleId: 'com.example.codecelixTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwvePvF7jb04K6LisfoBoonR0vBYGoJX8',
    appId: '1:896887756807:ios:54a1115ece543f639572a2',
    messagingSenderId: '896887756807',
    projectId: 'codecelixtaskmanager-f8557',
    storageBucket: 'codecelixtaskmanager-f8557.firebasestorage.app',
    iosBundleId: 'com.example.codecelixTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUggyWXIxDpu8Bfg0I_foyDrJXUWhPS-w',
    appId: '1:896887756807:web:df89b7253e9c0bc89572a2',
    messagingSenderId: '896887756807',
    projectId: 'codecelixtaskmanager-f8557',
    authDomain: 'codecelixtaskmanager-f8557.firebaseapp.com',
    storageBucket: 'codecelixtaskmanager-f8557.firebasestorage.app',
    measurementId: 'G-VQPNSRRN7Z',
  );
}
